# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, verbose_name='Модель устройства')),
                ('type', models.CharField(blank=True, default=None, max_length=255, verbose_name='Тип устройства')),
            ],
        ),
    ]
