# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20170616_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=255, verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name_plural': 'Типы',
                'verbose_name': 'Тип',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Type', verbose_name='Тип устройства'),
        ),
    ]
