# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20170616_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Картинка'),
        ),
    ]
