# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_type_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
