# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crash',
            old_name='id_device',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='crash',
            old_name='ids_rp',
            new_name='rps',
        ),
    ]
