# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0003_auto_20170616_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crash',
            name='date',
        ),
    ]
