# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0004_remove_crash_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Картинка'),
        ),
    ]
