# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0005_crash_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='rps',
            field=models.ManyToManyField(blank=True, to='repairparts.RepairParts', verbose_name='Детали'),
        ),
    ]
