# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0006_auto_20170622_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crash',
            name='percent_cost',
        ),
    ]
