# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.CharField(default='', max_length=255, verbose_name='Ссылка на аватар человека')),
                ('feedback_link', models.CharField(default='', max_length=255, verbose_name='Ссылка на отзыв')),
                ('feedback_image', models.CharField(default='', max_length=255, verbose_name='Ссылка на картинку')),
                ('user_nickname', models.CharField(default='', max_length=255, verbose_name='Никнейм')),
                ('feedback_likes', models.IntegerField(default=100, verbose_name='КОл-во лайков')),
                ('feedback_comments', models.IntegerField(default=10, verbose_name='Кол-во коментов')),
                ('feedback_text', models.CharField(default='', max_length=255, verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name_plural': 'отзывы',
                'verbose_name': 'отзыв',
            },
        ),
    ]
