# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semen', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст отзыва'),
        ),
    ]
