# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semen', '0003_auto_20170810_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(default='', max_length=5000, verbose_name='Текст отзыва'),
        ),
    ]
