# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semen', '0004_auto_20170810_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на аккаунт человека'),
        ),
    ]
