# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '__first__'),
        ('crashes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время заявки')),
                ('address', models.CharField(blank=True, default=None, max_length=255, verbose_name='Адрес клиента')),
                ('phone', models.CharField(blank=True, default=None, max_length=255, verbose_name='Телефон клиента')),
                ('name', models.CharField(blank=True, default=None, max_length=255, verbose_name='Имя клиента')),
                ('travel_time', models.DateTimeField(default=None, verbose_name='Приблизительное время поезки')),
                ('total_cost', models.IntegerField()),
                ('id_device', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device', verbose_name='Устройство')),
                ('ids_crash', models.ManyToManyField(blank=True, to='crashes.Crash', verbose_name='Поломки')),
            ],
        ),
    ]
