# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170616_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='travel_time',
            field=models.IntegerField(default=0, verbose_name='Приблизительное время поезки(в минутах)'),
        ),
    ]
