# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170616_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROGRESS', 'Принят'), ('CANCELED', 'Слился'), ('DONE', 'Cделан')], default='NEW', max_length=100),
        ),
    ]
