# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170616_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
