# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170622_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='travel_time',
        ),
    ]
